# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: sectigo

steps:

- task: DownloadSecureFile@1
  displayName: Download Certificate
  inputs:
    secureFile: 'sectigo2025.pfx'

- task: PowerShell@2
  displayName: import Certificate
  inputs:
    targetType: 'inline'
    script: |
      $pfx = "$env:DOWNLOADSECUREFILE_SECUREFILEPATH"
      $pw = "$(CertPass2025)"
      $pfxpass = $pw | ConvertTo-SecureString -AsPlainText -Force
      Import-PfxCertificate -FilePath $pfx -CertStoreLocation Cert:\CurrentUser\My -Password $pfxpass 

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'x86'
    configuration: 'Release'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'x64'
    configuration: 'Release'

- task: CopyFiles@2
  displayName: 'Copy SPFx WebPart to artifacts'
  inputs:
    Contents: ship/*.msi
    flattenFolders: true
    TargetFolder: '$(Build.ArtifactStagingDirectory)/ship'

- publish: $(Build.ArtifactStagingDirectory)/ship
  artifact: ship
